tinyMCE.addI18n('pt.advimage_dlg',{
tab_general:"Geral",
tab_appearance:"Aparência",
tab_advanced:"Avançado",
general:"Geral",
title:"Título",
preview:"Pré-visualizar",
constrain_proportions:"Restringir proporções",
langdir:"Direção do idioma",
langcode:"Código do idioma",
long_desc:"Descrição completa do link",
style:"Estilo",
classes:"Classes",
ltr:"Esquerda para a direita",
rtl:"Direita para a esquerda",
id:"Id",
map:"Mapa de imagem",
swap_image:"Trocar imagem",
alt_image:"Imagem alternativa",
mouseover:"para mouse sobre",
mouseout:"para mouse fora",
misc:"Miscelâneas",
example_img:"Aparência da imagem de pré-visualização",
missing_alt:"Tem certeza de que deseja continuar sem incluir uma descrição da imagem? Sem ela, a imagem pode não ser acessível a alguns usuários com deficiência, ou para aqueles que usam um navegador de texto ou navegação na Web sem imagens.",
dialog_title:"Inserir/editar imagem",
src:"URL da imagem",
alt:"Descrição da imagem",
list:"Lista de imagens",
border:"Borda",
dimensions:"Dimensões",
width:"Largura",
height:"Altura",
vspace:"Espaço na vertical",
hspace:"Espaço na horizontal",
align:"Alinhamento",
align_baseline:"Linha Base",
align_top:"Topo",
align_middle:"Meio",
align_bottom:"Abaixo",
align_texttop:"Texto acima",
align_textbottom:"Texto abaixo",
align_left:"Esquerda",
align_right:"Direita",
image_list:"Imagem da Lista"
});
