tinyMCE.addI18n('pt.media_dlg',{
title:"Inserir/editar mídia embutida",
general:"Geral",
advanced:"Avançado",
file:"Arquivo/URL",
list:"Lista",
size:"Dimensões",
preview:"Pré-visualizar",
constrain_proportions:"Restringir proporções",
type:"Tipo",
id:"Id",
name:"Nome",
class_name:"Classe",
vspace:"V-Space",
hspace:"H-Space",
play:"Início automático (auto play)",
loop:"Loop",
menu:"Exibir menu",
quality:"Qualidade",
scale:"Escala",
align:"Alinhar",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Fundo",
base:"Base",
flashvars:"Variáveis flash",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Ocultar",
controller:"Controlador",
kioskmode:"Modo Kiosk",
playeveryframe:"Executar cada frame",
targetcache:"Cache alvo",
correction:"Sem correção",
enablejavascript:"Ativar JavaScript",
starttime:"Hora de início",
endtime:"Hora de término",
href:"Href",
qtsrcchokespeed:"Diminuir velocidade",
target:"Alvo",
volume:"Volume",
autostart:"Início automático",
enabled:"Ativado",
fullscreen:"Tela cheia",
invokeurls:"Invocar URLs",
mute:"Mudo",
stretchtofit:"Esticar para caber",
windowlessvideo:"Vídeo sem janela",
balance:"Balanço",
baseurl:"URL base",
captioningid:"ID da legenda",
currentmarker:"Marcador atual",
currentposition:"Posição atual",
defaultframe:"Frame padrão",
playcount:"Iniciar contador",
rate:"Taxa",
uimode:"Modo UI",
flash_options:"Opções Flash",
qt_options:"Opções Quicktime",
wmp_options:"Opções Windows Media Player",
rmp_options:"Opções Real Player",
shockwave_options:"Opções Shockwave",
autogotourl:"Ir para URL automaticamente",
center:"Centralizar",
imagestatus:"Estado da imagem",
maintainaspect:"Manter as proporções",
nojava:"Sem Java",
prefetch:"Antecipar",
shuffle:"Misturar",
console:"Terminal",
numloop:"Repetições",
controls:"Controles",
scriptcallbacks:"Chamadas de scripts",
swstretchstyle:"Estilo do esticar",
swstretchhalign:"Esticar a Horizontal (H-Align)",
swstretchvalign:"Esticar a Vertical (V-Align)",
sound:"Som",
progress:"Progresso",
qtsrc:"QT Src",
qt_stream_warn:"Recursos de stream rtsp devem ser adicionados ao campo QT Src na guia avançada.\nTambém é possível adicionar uma versão sem stream ao campo Src (origem)",
align_top:"Topo",
align_right:"Direita",
align_bottom:"Abaixo",
align_left:"Esquerda",
align_center:"Centro",
align_top_left:"Topo esquerdo",
align_top_right:"Topo direito",
align_bottom_left:"Inferior esquerdo",
align_bottom_right:"Inferior direito",
flv_options:"Opções de vídeo Flash",
flv_scalemode:"Modo de escala",
flv_buffer:"Buffer",
flv_starttime:"Hora de início",
flv_defaultvolume:"Volume padrão",
flv_hiddengui:"Ocultar GUI",
flv_autostart:"Início automático",
flv_loop:"Repetição",
flv_showscalemodes:"Mostrar modos de escala",
flv_smoothvideo:"Suavizar video",
flv_jscallback:"Chamada do JS",
html5_video_options:"Opções de vídeo HTML5",
altsource1:"Origem alternativa 1",
altsource2:"Origem alternativa 2",
preload:"Pré-carregar",
poster:"Cartaz",

source:"Fonte"
});
