tinyMCE.addI18n('pt.table_dlg',{
general_tab:"Geral",
advanced_tab:"Avançado",
general_props:"Propriedades gerais",
advanced_props:"Propriedades avançadas",
rowtype:"Linha em parte da tabela",
title:"Inserir/Modificar tabela",
width:"Largura",
height:"Altura",
cols:"Colunas",
rows:"Linhas",
cellspacing:"Espaçamento das células (cellspacing)",
cellpadding:"Preenchimento de células (padding)",
border:"Borda",
align:"Alinhamento",
align_default:"Padrão",
align_left:"Esquerda",
align_right:"Direita",
align_middle:"Centro",
row_title:"Propriedades da linha da tabela",
cell_title:"Propriedades da célula da tabela",
cell_type:"Tipo de célula",
valign:"Alinhamento vertical",
align_top:"Topo",
align_bottom:"Abaixo",
bordercolor:"Cor da borda",
bgcolor:"Cor de fundo",
merge_cells_title:"Mesclar células da tabela",
id:"Id",
style:"Estilo",
langdir:"Direção do idioma",
langcode:"Código do idioma",
mime:"Tipo MIME Alvo",
ltr:"Esquerda para a direita",
rtl:"Direita para a esquerda",
bgimage:"Imagem de fundo",
summary:"Sumário",
td:"Data",
th:"Cabeçalho",
cell_cell:"Atualizar célula atual",
cell_row:"Atualizar todas as células na linha",
cell_col:"Atualizar todas as células na coluna",
cell_all:"Atualizar todas as células da tabela",
row_row:"Atualizar a linha atual",
row_odd:"Atualizar linhas ímpares (odd) da tabela",
row_even:"Atualizar linhas pares (even) na tabela",
row_all:"Atualizar todas as linhas da tabela",
thead:"Cabeçalho da Tabela",
tbody:"Corpo da Tabela",
tfoot:"Rodapé da Tabela",
scope:"Escopo",
rowgroup:"Grupo de Linhas",
colgroup:"Grupo de Colunas",
col_limit:"Você excedeu o máximo permitido de {$cols} colunas.",
row_limit:"Você execedeu o máximo permitido de {$rows} linhas",
cell_limit:"Você excedeu o máximo permitido de {$cells} células",
missing_scope:"Você não especificou o escopo para o cabeçalho da célula dessa tabela. Sem esse elemento, portadores de deficiência podem ter dificuldades de entender os dados nela contida, pois isso atrapalha a interpretação do sistema.",
caption:"Título da tabela",
frame:"Frame",
frame_none:"nenhum",
frame_groups:"grupos",
frame_rows:"linhas",
frame_cols:"colunas",
frame_all:"todos",
rules:"Regras",
rules_void:"vazio (void)",
rules_above:"acima",
rules_below:"abaixo",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"caixa (box)",
rules_border:"borda"
});
