tinyMCE.addI18n('pt.style_dlg',{
title:"Editar Estilo CSS",
apply:"Aplicar",
text_tab:"Texto",
background_tab:"Fundo",
block_tab:"Bloco",
box_tab:"Caixa",
border_tab:"Borda",
list_tab:"Lista",
positioning_tab:"Posicionamento",
text_props:"Texto",
text_font:"Fonte",
text_size:"Tamanho",
text_weight:"Largura",
text_style:"Estilo",
text_variant:"Variante",
text_lineheight:"Altura da linha",
text_case:"Caixa",
text_color:"Cor",
text_decoration:"Decoração",
text_overline:"sobrescrito",
text_underline:"sublinhado",
text_striketrough:"rasurado",
text_blink:"piscante",
text_none:"nenhum",
background_color:"Cor de fundo",
background_image:"Imagem de fundo",
background_repeat:"Repetir",
background_attachment:"Anexo",
background_hpos:"Posição horizontal",
background_vpos:"Posição vertical",
block_wordspacing:"Espaçamento da palavra",
block_letterspacing:"Espaçamento da letra",
block_vertical_alignment:"Alinhamento vertical",
block_text_align:"Alinhamento do texto",
block_text_indent:"Recuo do texto",
block_whitespace:"Espaço em branco",
block_display:"Exibir",
box_width:"Largura",
box_height:"Altura",
box_float:"Flutuar",
box_clear:"Limpar",
padding:"Espaçamento",
same:"Mesmo para todos",
top:"Topo",
right:"Direita",
bottom:"Abaixo",
left:"Esquerda",
margin:"Margem",
style:"Estilo",
width:"Largura",
height:"Altura",
color:"Cor",
list_type:"Tipo",
bullet_image:"Imagem bullet",
position:"Posição",
positioning_type:"Tipo",
visibility:"Visibilidade",
zindex:"Z-index",
overflow:"Transbordamento",
placement:"Localização",
clip:"Clip",
text:"Texto",
background:"Fundo",
block:"Bloco",
box:"Caixa",
border:"Borda",
list:"Lista",
position:"Posição"
});
