tinyMCE.addI18n('pt.fullpage_dlg',{
title:"Propriedades do documento",
meta_tab:"Geral",
appearance_tab:"Aparência",
advanced_tab:"Avançado",
meta_props:"Informações Meta",
langprops:"Idioma e codificação",
meta_title:"Título",
meta_keywords:"Palavras-chaves",
meta_description:"Descrição",
meta_robots:"Robôs",
doctypes:"Doctype",
langcode:"Código do idioma",
langdir:"Direção do idioma",
ltr:"Esquerda para a direita",
rtl:"Direita para a esquerda",
xml_pi:"Declaração XML",
encoding:"Codificação de caracteres",
appearance_bgprops:"Propriedades do fundo",
appearance_marginprops:"Margens do corpo",
appearance_linkprops:"Cores do link",
appearance_textprops:"Propriedades do texto",
bgcolor:"Cor de fundo",
bgimage:"Imagem de fundo",
left_margin:"Margem esquerda",
right_margin:"Margem direita",
top_margin:"Margem superior",
bottom_margin:"Margem inferior",
text_color:"Cor do texto",
font_size:"Tamanho da fonte",
font_face:"Tipo de fonte",
link_color:"Cor do link",
hover_color:"Cor do link (selecionado)",
visited_color:"Cor do link (visitado)",
active_color:"Cor do link (ativado)",
textcolor:"Cor",
fontsize:"Tamanho da fonte",
fontface:"Família da fonte",
meta_index_follow:"Indexar e seguir links",
meta_index_nofollow:"Indexar e não seguir links",
meta_noindex_follow:"Não indexar, mas seguir links",
meta_noindex_nofollow:"Não indexar e não seguir links",
appearance_style:"Propriedades de estilo",
stylesheet:"Folha de Estilo",
style:"Estilo",
author:"Autor",
copyright:"Direitos Autorais",
add:"Adicionar novo elemento",
remove:"Remover elemento selecionado",
moveup:"Mover para cima o elemento selecionado",
movedown:"Mover para baixo o elemento selecionado",
head_elements:"Elementos do cabeçalho",
info:"Informação",
add_title:"Título do elemento",
add_meta:"Elemento Meta",
add_script:"Script do elemento",
add_style:"Estilo do elemento",
add_link:"Link do elemento",
add_base:"Elemento base",
add_comment:"Adicionar comentário",
title_element:"Título do elemento",
script_element:"Script do elemento",
style_element:"Estilo do elemento",
base_element:"Elemento base",
link_element:"Link do elemento",
meta_element:"Elemento Meta",
comment_element:"Comentário",
src:"Scr",
language:"Idioma",
href:"Href",
target:"Alvo",
type:"Tipo",
charset:"Codificação de Caracteres",
defer:"Adiar",
media:"Mídia",
properties:"Propriedades",
name:"Nome",
value:"Valor",
content:"Conteúdo",
rel:"Rel",
rev:"Revisão",
hreflang:"Idioma do Link",
general_props:"Geral",
advanced_props:"Avançado"
});
