tinyMCE.addI18n('pt.advlink_dlg',{
title:"Inserir/editar link",
url:"URL do Link",
target:"Alvo",
titlefield:"Título",
is_email:"A URL que você digitou parece ser um endereço de e-mail. Você quer adicionar o prefixo 'mailto:'?",
is_external:"A URL que você digitou parece ser um link externo. Você quer adicionar o prefixo 'http://'?",
list:"Lista de links",
general_tab:"Geral",
popup_tab:"Popup",
events_tab:"Eventos",
advanced_tab:"Avançado",
general_props:"Propriedades gerais",
popup_props:"Configurações do Popup",
event_props:"Eventos",
advanced_props:"Propriedades avançadas",
popup_opts:"Opções",
anchor_names:"Âncoras",
target_same:"Abrir nesta janela / frame",
target_parent:"Abrir na janela pai / frame",
target_top:"Abrir no frame superior (substituir todos os frames)",
target_blank:"Abrir em uma nova janela",
popup:"Popup JavaScript",
popup_url:"URL do Popup",
popup_name:"Nome da janela",
popup_return:"Inserir 'retorno falso'",
popup_scrollbars:"Exibir barras de rolagem",
popup_statusbar:"Exibir barra de status",
popup_toolbar:"Exibir barra de ferramentas",
popup_menubar:"Exibir barra de menu",
popup_location:"Exibir barra de localização",
popup_resizable:"Tornar a janela redimensionável",
popup_dependent:"Dependente (somente Mozilla/Firefox)",
popup_size:"Tamanho",
width:"Largura",
height:"Altura",
popup_position:"Posição (X/Y)",
id:"Id",
style:"Estilo",
classes:"Classes",
target_name:"Nome do alvo",
langdir:"Direção do idioma",
target_langcode:"Idioma alvo",
langcode:"Código do idioma",
encoding:"Codificação de caracteres do alvo",
mime:"Tipo MIME Alvo",
rel:"Relacionamento da página com o alvo",
rev:"Relacionamento do alvo com a página",
tabindex:"Tabindex",
accesskey:"Chave de acesso",
ltr:"Esquerda para a direita",
rtl:"Direita para a esquerda",
link_list:"Lista de links"
});
