tinyMCE.addI18n('pt.advanced',{
style_select:"Estilos",
font_size:"Tamanho da fonte",
fontdefault:"Família da fonte",
block:"Formato",
paragraph:"Parágrafo",
div:"Div",
address:"Endereço",
pre:"Preformatação",
h1:"Título 1",
h2:"Título 2",
h3:"Título 3",
h4:"Título 4",
h5:"Título 5",
h6:"Título 6",
blockquote:"Citação",
code:"Código",
samp:"Exemplo de código",
dt:"Termo de definição",
dd:"Descrição da definição",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"Itálico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Rasurado",
justifyleft_desc:"Alinhar à esquerda",
justifycenter_desc:"Centralizar",
justifyright_desc:"Alinhar à direita",
justifyfull_desc:"Justificar",
bullist_desc:"Lista desordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Não identar",
indent_desc:"Identar",
undo_desc:"Desfazer (Crtl+Z)",
redo_desc:"Refazer (Crtl+Y)",
link_desc:"Inserir/editar link",
unlink_desc:"Retirar link",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar código",
code_desc:"Editar código HTML",
sub_desc:"Subscrito",
sup_desc:"Sobrescrito",
hr_desc:"Inserir linha horizontal",
removeformat_desc:"Remover formatação",
custom1_desc:"Insira aqui a descrição",
forecolor_desc:"Selecione a cor da fonte",
backcolor_desc:"Selecionar cor de fundo",
charmap_desc:"Inserir caracter especial",
visualaid_desc:"Alterar definições/elementos invisíveis",
anchor_desc:"Inserir/editar âncora",
cut_desc:"Recortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Citação",
clipboard_msg:"Copiar/Cortar/Colar não estão disponíveis no Mozilla Firefox.\r\nVocê gostaria de mais informações sobre esse problema?",
path:"Caminho",
newdocument:"Gostaria realmente de apagar todo o conteúdo?",
toolbar_focus:"Ir para as ferramentas - Alt+Q, Ir para o editor - Alt-Z, Ir para o caminho do elemento - Alt-X",
more_colors:"Mais cores",

// Accessibility Strings
shortcuts_desc:'Ajuda de Acessibilidade',
help_shortcut:'. Pressione ALT F10 para barra de ferramentas. Pressione ALT 0 para ajuda.',
rich_text_area:"Área de Rich Text",
toolbar:"Barra de Ferramentas"
});
