tinyMCE.addI18n('pt.advanced_dlg',{
about_title:"Sobre o TinyMCE",
about_general:"Sobre",
about_help:"Ajuda",
about_license:"Licença",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Versão",
about_loaded:"Plugins carregados",
anchor_title:"Inserir/editar âncora",
anchor_name:"Nome da âncora",
anchor_invalid:"Por favor, insira um nome válido para a âncora",
code_title:"Editor de Código HTML",
code_wordwrap:"Quebra de linha",
colorpicker_title:"Selecionar uma cor",
colorpicker_picker_tab:"Seletor",
colorpicker_picker_title:"Seletor de cores",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta de cores",
colorpicker_named_tab:"Nomeadas",
colorpicker_named_title:"Cores nomeadas",
colorpicker_color:"Cor:",
colorpicker_name:"Nome:",
charmap_title:"Selecionar caracter personalizado",
image_title:"Inserir/editar imagem",
image_src:"URL da imagem",
image_alt:"Descrição da imagem",
image_list:"Lista de imagens",
image_border:"Borda",
image_dimensions:"Dimensões",
image_vspace:"Espaço na vertical",
image_hspace:"Espaço na horizontal",
image_align:"Alinhamento",
image_align_baseline:"Alinhar à base",
image_align_top:"Topo",
image_align_middle:"Meio",
image_align_bottom:"Abaixo",
image_align_texttop:"Texto acima",
image_align_textbottom:"Texto abaixo",
image_align_left:"Esquerda",
image_align_right:"Direita",
link_title:"Inserir/editar link",
link_url:"URL do Link",
link_target:"Alvo (Target)",
link_target_same:"Abrir o link na mesma janela",
link_target_blank:"Abrir o link em nova janela",
link_titlefield:"Título",
link_is_email:"A URL que você digitou parece ser um endereço de e-mail. Você quer adicionar o prefixo 'mailto:'?",
link_is_external:"A URL inserida parece um link externo. Gostaria de adicionar o prefixo http:// ?",
link_list:"Lista de links",
accessibility_help:"Ajuda de Acessibilidade",
accessibility_usage_title:"Uso Geral"
});
