tinyMCE.addI18n('pt.xhtmlxtras_dlg',{
attribute_label_title:"Título",
attribute_label_id:"ID",
attribute_label_class:"Classe",
attribute_label_style:"Estilo",
attribute_label_cite:"Citar",
attribute_label_datetime:"Data/hora",
attribute_label_langdir:"Direção do texto",
attribute_option_ltr:"Esquerda para a direita",
attribute_option_rtl:"Direita para a esquerda",
attribute_label_langcode:"Idioma",
attribute_label_tabindex:"TabIndex",
attribute_label_accesskey:"Chave de Acesso",
attribute_events_tab:"Eventos",
attribute_attrib_tab:"Atributos",
general_tab:"Geral",
attrib_tab:"Atributos",
events_tab:"Eventos",
fieldset_general_tab:"Configurações Gerais",
fieldset_attrib_tab:"Atributos do Elemento",
fieldset_events_tab:"Eventos do Elemento",
title_ins_element:"Inserção do Elemento",
title_del_element:"Remoção do Elemento",
title_acronym_element:"Acrônimo do Elemento",
title_abbr_element:"Abreviação do Elemento",
title_cite_element:"Citação do Elemento",
remove:"Remover",
insert_date:"Inserir data/hora atual",
option_ltr:"Esquerda para a direita",
option_rtl:"Direita para a esquerda",
attribs_title:"Inserir/Editar Atributos"
});
